### ISSUE TITLE
Getting "Unexpected token import" with fresh install

### ISSUE THREAD

**Issue by scottschafer** [lokeshthegenius/generator-node-express-ts#3]
^C5091-MBP15:sip2 sschafer$ gulp
[09:50:35] Using gulpfile ~/projhome/contract/sip2/gulpfile.js
[09:50:35] Starting 'compile'...
[09:50:37] Finished 'compile' after 1.66 s
[09:50:37] Starting 'watch'...
[09:50:37] Finished 'watch' after 334 ms
[09:50:37] Starting 'default'...
[09:50:37] Finished 'default' after 453 μs
[09:50:37] [nodemon] 1.14.9
[09:50:37] [nodemon] to restart at any time, enter `rs`
[09:50:37] [nodemon] watching: *.*
[09:50:37] [nodemon] starting `node bin/www.ts`
/Users/sschafer/projhome/contract/sip2/bin/www.ts:3
import { app } from '../app';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)

**Comment by soniAnkur** [comment]
Getting the same problem
